import express from 'express';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import * as XLSX from 'xlsx';
import * as db from './db.js';
import * as D from '../shared/domain.js';
import {enrichProductSpecs, batchEnrichCatalog} from '../shared/spec-intelligence.js';
import {demoProducts} from './seed.js';
import {initializeBrands,registerBrandRoutes} from './brands.js';
await db.init();
await initializeBrands();
const app=express(),port=Number(process.env.PORT||4173);
app.disable('x-powered-by');app.use(helmet({contentSecurityPolicy:false,crossOriginResourcePolicy:{policy:'same-site'}}));app.use(express.json({limit:'5mb'}));
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!['GET','HEAD'].includes(req.method)&&req.headers.origin&&req.headers.origin!==`${req.protocol}://${req.get('host')}`)return res.status(403).json({error:'Nguồn yêu cầu không hợp lệ'});next();});
const fail=(message,status=400)=>Object.assign(new Error(message),{status});
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const hash=s=>crypto.createHash('sha256').update(s).digest('hex');
const now=()=>new Date().toISOString();
const cleanUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:u.active});
async function audit(user,action,subject,before=null,after=null){await db.put('audit',{id:crypto.randomUUID(),at:now(),user:user.name,userId:user.id,action,subject,before,after});}
async function session(res,user){const token=crypto.randomBytes(32).toString('hex');await db.put('sessions',{id:hash(token),userId:user.id,expires:Date.now()+8*3600000});res.cookie('vg_session',token,{httpOnly:true,sameSite:'strict',secure:process.env.COOKIE_SECURE==='true',maxAge:8*3600000,path:'/'});}
const limit=rateLimit({windowMs:15*60*1000,limit:30,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'Quá nhiều lần đăng nhập. Hãy thử lại sau 15 phút.'}});
app.get('/api/status',asyncRoute(async(req,res)=>res.json({setup:(await db.all('users')).length===0,storage:db.dbMode})));
app.post('/api/setup',limit,asyncRoute(async(req,res)=>db.transaction(async()=>{if((await db.all('users')).length)throw fail('Hệ thống đã được thiết lập',409);const {name,email,password}=req.body;if(!name||!/^\S+@\S+\.\S+$/.test(email)||!password||password.length<10)throw fail('Nhập tên, email hợp lệ và mật khẩu ít nhất 10 ký tự');const user={id:crypto.randomUUID(),name,email:email.toLowerCase(),password:await bcrypt.hash(password,12),role:'admin',active:true};await db.put('users',user);await db.put('settings',{id:'weights',...D.defaultWeights});await session(res,user);await audit(user,'Khởi tạo hệ thống','Tài khoản quản trị');res.json(cleanUser(user));})));
app.post('/api/login',limit,asyncRoute(async(req,res)=>{const user=(await db.all('users')).find(u=>u.email===String(req.body.email).toLowerCase());if(!user?.active||!await bcrypt.compare(String(req.body.password||''),user.password))throw fail('Email hoặc mật khẩu không đúng',401);await session(res,user);res.json(cleanUser(user));}));
app.use('/api',asyncRoute(async(req,res,next)=>{const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('vg_session='))?.slice(11);const s=token&&await db.get('sessions',hash(token));const u=s&&s.expires>Date.now()&&await db.get('users',s.userId);if(!u?.active)throw fail('Vui lòng đăng nhập',401);req.user=u;next();}));
const permit=(req,roles)=>{if(!roles.includes(req.user.role))throw fail('Bạn không có quyền thực hiện chức năng này',403);};
const sanitize=(p,role)=>{const q={...p};if(!D.canFinance(role)){D.privateKeys.forEach(k=>delete q[k]);delete q.raw;delete q.normalized;q.priceHistory=(p.priceHistory||[]).map(h=>({...h,changes:h.changes.filter(c=>!D.privateKeys.includes(c.field))})).filter(h=>h.changes.length);}return q;};
async function settings(){const w=await db.get('settings','weights');return Object.fromEntries(Object.keys(D.defaultWeights).map(k=>[k,w?.[k]??D.defaultWeights[k]]));}
async function publicProduct(p,role,products,w){const q=sanitize(p,role);q.suggestions=D.own(p)?[]:D.candidates(p,products);const reviewed=await db.get('matches',p.id);q.matching=reviewed&&reviewed.status!=='AI đề xuất'?reviewed.ids.map(id=>{const target=products.find(t=>t.id===id);return target?{id,...D.similarity(p,target)}:null;}).filter(Boolean):q.suggestions;q.gap=D.own(p)?null:D.gap(p,products);q.dataMissing=D.matchingRequired.filter(k=>!D.has(p[k]));if(!D.has(p.capacity)&&!D.has(p.dimensions))q.dataMissing.push('capacity');q.score=D.competition(p,products,w);if(!D.canFinance(role)){q.score={score:q.score.score,level:q.score.level,confidence:q.score.confidence,missing:q.score.missing};}else{q.financial=D.finance(p);q.recommendation=D.recommendation(p,products,w);}return q;}
registerBrandRoutes(app);
app.use('/api/assets',express.static(path.join(db.dataDir,'assets'),{index:false,dotfiles:'deny'}));
app.get('/api/me',(req,res)=>res.json(cleanUser(req.user)));
app.post('/api/logout',asyncRoute(async(req,res)=>{const token=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('vg_session='))?.slice(11);if(token)await db.remove('sessions',hash(token));res.clearCookie('vg_session');res.json({ok:true});}));
app.get('/api/data',asyncRoute(async(req,res)=>{const p=await db.all('products'),w=await settings();res.json({products:await Promise.all(p.map(x=>publicProduct(x,req.user.role,p,w))),matches:await db.all('matches'),weights:w,opportunities:(await db.all('opportunities')).map(o=>{const copy={...o};if(!D.canFinance(req.user.role))delete copy.targetCost;return copy;}),proposals:await db.all('proposals'),follows:(await db.all('follows')).filter(f=>f.userId===req.user.id),imports:(await db.all('imports')).map(({raw,...x})=>x)});}));
function productInput(input){const p={};for(const f of D.fields){if(!Object.hasOwn(input,f.key))continue;let v=input[f.key];if(D.numeric.includes(f.key))v=D.has(v)?Number(v):null;if(v!==undefined)p[f.key]=v;}return p;}
const duplicate=(p,products,ignore)=>products.find(q=>q.id!==ignore&&(D.norm(q.code)===D.norm(p.code)||(D.has(p.model)&&D.norm(q.model)===D.norm(p.model))||D.norm(q.name)===D.norm(p.name)));
async function saveProduct(req,input,id,allowDuplicate=false,deferMatches=false){
 const previous=id?await db.get('products',id):null;if(id&&!previous)throw fail('Không tìm thấy sản phẩm',404);
 if(!previous)permit(req,['admin','leader']);
 const incoming=productInput(input);for(const key of Object.keys(incoming))if(!D.editable(req.user.role,key)&&JSON.stringify(incoming[key])!==JSON.stringify(previous?.[key]))throw fail('Không có quyền sửa '+D.labels[key],403);
 const p={...previous,...incoming};const errors=D.validate(p);if(errors.length)throw fail(errors.map(e=>D.labels[e.field]+': '+e.message).join('; '));
 const products=await db.all('products');if(!allowDuplicate&&duplicate(p,products,id))throw fail('Trùng mã, model hoặc tên sản phẩm. Hãy kiểm tra lại.',409);
 if(products.some(q=>q.id!==id&&D.norm(q.code)===D.norm(p.code)))throw fail('Mã sản phẩm đã tồn tại',409);
 const n=D.normalizeProduct(p);p.normalized=n.data;delete p.normalized.raw;delete p.normalized.normalized;delete p.normalized.priceHistory;
 p.raw={...(previous?.raw||{}),...incoming};p.warnings=n.warnings;p.normalizationConfirmed=null;p.id=id||crypto.randomUUID();p.updatedAt=now();p.updatedBy=req.user.name;
 const priceChanges=D.fields.filter(f=>f.group==='prices'&&previous?.[f.key]!==p[f.key]).map(f=>({field:f.key,before:previous?.[f.key]??null,after:p[f.key]??null}));
 p.priceHistory=[...(previous?.priceHistory||[]),...(priceChanges.length?[{at:now(),by:req.user.name,changes:priceChanges}]:[])];
 await db.put('products',p);await audit(req.user,previous?'Cập nhật sản phẩm':'Thêm sản phẩm',p.code,previous,p);
 // Recompute only unreviewed suggestions. Reviewed and rejected pairs remain explicit decisions.
 if(!deferMatches){const all=await db.all('products');for(const rival of all.filter(p=>!D.own(p)))await refreshMatches(rival,all);}
 return p;
}
async function refreshMatches(p,products){const old=await db.get('matches',p.id);if(old&&old.status!=='AI đề xuất')return;await db.put('matches',{id:p.id,ids:D.candidates(p,products).map(c=>c.id),status:'AI đề xuất',at:now()});}
app.post('/api/products',asyncRoute(async(req,res)=>db.transaction(async()=>{const p=await saveProduct(req,req.body);res.json({id:p.id});})));
app.put('/api/products/:id',asyncRoute(async(req,res)=>db.transaction(async()=>{const p=await saveProduct(req,req.body,req.params.id);res.json({id:p.id});})));
app.delete('/api/products/:id',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader']);if(req.body.confirm!==true)throw fail('Cần xác nhận xóa');const p=await db.get('products',req.params.id);if(!p)throw fail('Không tìm thấy',404);await db.remove('products',p.id);await db.remove('matches',p.id);for(const m of await db.all('matches'))if(m.ids.includes(p.id))await db.put('matches',{...m,ids:m.ids.filter(x=>x!==p.id),status:'AI đề xuất'});for(const c of ['opportunities','proposals','follows'])for(const v of await db.all(c))if(v.productId===p.id)await db.remove(c,v.id);await audit(req.user,'Xóa sản phẩm',p.code,p);res.json({ok:true});})));
app.post('/api/products/:id/normalize',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader']);const p=await db.get('products',req.params.id);if(!p)throw fail('Không tìm thấy',404);const normalized=D.normalizeProduct(p);const updated={...p,...productInput(normalized.data),normalizationConfirmed:{by:req.user.name,at:now()},normalized:productInput(normalized.data)};await db.put('products',updated);await audit(req.user,'Xác nhận chuẩn hóa',p.code,p,updated);res.json({ok:true});})));
app.post('/api/matches/:id',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader','sales']);const p=await db.get('products',req.params.id),products=await db.all('products');if(!p||D.own(p))throw fail('Chỉ ghép sản phẩm đối thủ');const ids=[...new Set(req.body.ids||[])];if(ids.length>3||ids.some(id=>!products.find(p=>p.id===id&&D.own(p))))throw fail('Chọn tối đa 3 sản phẩm Lock&King');const m={id:p.id,ids,status:ids.length?'Đã kiểm duyệt':'Đã hủy',by:req.user.name,at:now()};await db.put('matches',m);await audit(req.user,'Kiểm duyệt ghép cặp',p.code,null,m);res.json(m);})));
app.post('/api/follow/:id',asyncRoute(async(req,res)=>{const id=req.user.id+':'+req.params.id;if(await db.get('follows',id))await db.remove('follows',id);else await db.put('follows',{id,userId:req.user.id,productId:req.params.id});res.json({ok:true});}));
app.put('/api/weights',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['leader','admin']);const weights=Object.fromEntries(Object.keys(D.defaultWeights).map(k=>[k,Number(req.body[k])]));if(Object.values(weights).some(v=>!Number.isFinite(v)||v<0)||Math.abs(Object.values(weights).reduce((a,b)=>a+b,0)-100)>.001)throw fail('Trọng số phải không âm và tổng bằng 100');const before=await settings();await db.put('settings',{id:'weights',...weights});await audit(req.user,'Đổi trọng số','Chấm điểm',before,weights);res.json(weights);})));
app.put('/api/opportunities/:id',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader','purchasing']);const product=await db.get('products',req.params.id);if(!product||D.own(product))throw fail('Cơ hội phải gắn với sản phẩm đối thủ');const {status,notes,targetCost,suggestedPrice}=req.body;if(!D.opportunityStates.includes(status))throw fail('Trạng thái không hợp lệ');if(status==='Đã duyệt nhập'){permit(req,['leader','admin']);if(D.gap(product,await db.all('products'))!=='confirmed'||!D.has(targetCost)||!D.has(suggestedPrice)||!D.has(product.demand)||!D.has(product.inventoryRisk)||!D.has(product.assessmentSource)||!D.has(D.finance({...product,cost:Number(targetCost),sale:Number(suggestedPrice)}).net))throw fail('Chưa đủ dữ liệu xác định cơ hội, giá mục tiêu, lợi nhuận, nhu cầu hoặc rủi ro để duyệt nhập');}for(const v of [targetCost,suggestedPrice])if(D.has(v)&&(!Number.isFinite(Number(v))||Number(v)<0))throw fail('Giá phải không âm');const p={id:req.params.id,productId:req.params.id,status,notes:String(notes||''),targetCost:D.has(targetCost)?Number(targetCost):null,suggestedPrice:D.has(suggestedPrice)?Number(suggestedPrice):null,by:req.user.name,at:now()};await db.put('opportunities',p);await audit(req.user,'Cập nhật cơ hội',product.code,null,p);res.json(p);})));
app.post('/api/proposals/:id',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader','purchasing','sales']);const p=await db.get('products',req.params.id);if(!p)throw fail('Không tìm thấy',404);const status=req.body.status||'Chờ phê duyệt';if(!['Chờ phê duyệt','Đã duyệt nhập','Từ chối'].includes(status))throw fail('Trạng thái không hợp lệ');if(status!=='Chờ phê duyệt')permit(req,['leader','admin']);const rec=D.recommendation(p,await db.all('products'),await settings());if(status==='Đã duyệt nhập'&&rec.pending)throw fail(rec.reason);const proposal={id:p.id,productId:p.id,status,notes:String(req.body.notes||''),by:req.user.name,at:now()};await db.put('proposals',proposal);await audit(req.user,'Đề xuất nhập hàng',p.code,null,proposal);res.json(proposal);})));
app.get('/api/users',asyncRoute(async(req,res)=>{permit(req,['admin']);res.json((await db.all('users')).map(cleanUser));}));
app.post('/api/users',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin']);const {id,name,email,password,role,active}=req.body;if(!D.roles[role]||!name||!/^\S+@\S+\.\S+$/.test(email))throw fail('Kiểm tra tên, email và vai trò');const old=id?await db.get('users',id):null;if(!old&&(!password||password.length<10))throw fail('Mật khẩu ít nhất 10 ký tự');if(password&&password.length<10)throw fail('Mật khẩu ít nhất 10 ký tự');if(id===req.user.id&&(role!=='admin'||active===false))throw fail('Không thể tự khóa hoặc hạ quyền tài khoản đang dùng');if((await db.all('users')).some(u=>u.id!==id&&u.email===email.toLowerCase()))throw fail('Email đã tồn tại');const user={id:id||crypto.randomUUID(),name,email:email.toLowerCase(),role,active:active!==false,password:password?await bcrypt.hash(password,12):old.password};await db.put('users',user);if(old)for(const s of await db.all('sessions'))if(s.userId===id)await db.remove('sessions',s.id);await audit(req.user,'Quản lý tài khoản',email,null,cleanUser(user));res.json(cleanUser(user));})));
app.get('/api/audit',asyncRoute(async(req,res)=>{permit(req,['admin','leader']);res.json((await db.all('audit')).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,500));}));
app.post('/api/demo',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin']);if((await db.all('products')).length)throw fail('Chỉ nạp minh họa khi danh mục trống');for(const p of demoProducts())await db.put('products',{...p,updatedAt:now(),updatedBy:req.user.name,raw:{...p}});const products=await db.all('products');for(const p of products.filter(p=>!D.own(p)))await refreshMatches(p,products);await audit(req.user,'Nạp dữ liệu minh họa','11 sản phẩm');res.json({ok:true});})));
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:10*1024*1024}});
app.get('/api/template',(req,res)=>{permit(req,['admin','leader']);const wb=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet([D.fields.map(f=>f.label)]);sheet['!cols']=D.fields.map(()=>({wch:24}));XLSX.utils.book_append_sheet(wb,sheet,'Sản phẩm');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['HƯỚNG DẪN NHẬP DỮ LIỆU VŨ GIA'],['Bắt buộc: Mã sản phẩm, Tên sản phẩm, Thương hiệu, Nhóm ngành hàng.'],['Mỗi hàng một sản phẩm. Ô chưa biết để trống; số 0 có nghĩa là đã xác nhận bằng 0.'],['Tiền: số nguyên đồng; phí sàn, thuế, chiết khấu: phần trăm (8 = 8%).'],['Đơn vị: 500 ml, 3 l, 1.2 kg, 20 x 30 cm, 1.5 kW.'],['Ảnh: URL http/https. Không nhập công thức Excel.'],['Sheet Thông số mở rộng là tham khảo; nhập thông số vào cột Thông số mở rộng.'],['Dữ liệu minh họa của phần mềm không phải dữ liệu thị trường.']]),'Hướng dẫn');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Trường','Nhóm','Kiểu'],...D.fields.map(f=>[f.label,D.groups[f.group],f.type])]),'Danh mục');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Ví dụ nội dung cột Thông số mở rộng'],['Độ ồn: 40 dB\nTiêu chuẩn: Chưa xác minh']]),'Thông số mở rộng');sendWorkbook(res,wb,'Mau-nhap-Vu-Gia.xlsx');});
function sendWorkbook(res,wb,name){res.set('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.set('Content-Disposition',`attachment; filename="${name}"`);res.send(Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'})));}
app.post('/api/import/preview',upload.single('file'),asyncRoute(async(req,res)=>{permit(req,['admin','leader']);if(!req.file)throw fail('Chọn file Excel');const wb=XLSX.read(req.file.buffer,{type:'buffer',cellFormula:true,sheetRows:2002});const sheet=wb.Sheets[wb.SheetNames.includes('Sản phẩm')?'Sản phẩm':wb.SheetNames[0]];if(!sheet)throw fail('File không có trang dữ liệu');if(Object.values(sheet).some(v=>v&&typeof v==='object'&&v.f))throw fail('File chứa công thức. Hãy chuyển công thức thành giá trị trước khi nhập.');const matrix=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true});if(matrix.length>2001)throw fail('Mỗi lần nhập tối đa 2.000 dòng');if(!matrix.length)throw fail('File trống');const headers=matrix[0].map(String);if(new Set(headers).size!==headers.length)throw fail('Tên cột không được trùng');const rows=matrix.slice(1).map((values,i)=>({row:i+2,values})).filter(r=>r.values.some(D.has));const id=crypto.randomUUID();await db.put('importDrafts',{id,headers,rows,file:req.file.originalname,userId:req.user.id,at:now()});const mapping=headers.map(h=>D.fields.find(f=>D.norm(f.label)===D.norm(h)||D.norm(f.key)===D.norm(h)||(f.key==='npp'&&D.norm(h)==='gia npp'))?.key||'');res.json({id,headers,rows:rows.slice(0,20),count:rows.length,mapping});}));
function parseNumber(v){if(typeof v==='number')return v;let s=String(v).trim().replace(/\s|₫|đ|VND/gi,'');if(/^\d{1,3}(\.\d{3})+$/.test(s))s=s.replace(/\./g,'');else if(/^\d{1,3}(,\d{3})+$/.test(s))s=s.replace(/,/g,'');else s=s.replace(',','.');return Number(s);}
async function importRows(req){const draft=await db.get('importDrafts',req.body.id);if(!draft||draft.userId!==req.user.id)throw fail('Phiên nhập không tồn tại');const mapping=req.body.mapping||[];const selected=mapping.filter(Boolean);if(new Set(selected).size!==selected.length||selected.some(k=>!D.labels[k]))throw fail('Mỗi trường chỉ được ghép một cột');if(['code','name','brand','category'].some(k=>!selected.includes(k)))throw fail('Phải ghép đủ bốn cột bắt buộc');const products=await db.all('products');const seen=[...products];const result=[];for(const row of draft.rows){const p={};mapping.forEach((k,i)=>{if(k)p[k]=D.numeric.includes(k)?(D.has(row.values[i])?parseNumber(row.values[i]):null):String(row.values[i]??'');});const enrichedP=enrichProductSpecs(p);const errors=D.validate(enrichedP);const dup=duplicate(enrichedP,seen);const n=D.normalizeProduct(enrichedP);result.push({row:row.row,p:enrichedP,errors,duplicate:dup?{id:dup.id,code:dup.code}:null,warnings:n.warnings});seen.push({...enrichedP,id:'row-'+row.row});}return {draft,rows:result};}
app.post('/api/import/validate',asyncRoute(async(req,res)=>{permit(req,['admin','leader']);const result=await importRows(req);res.json({rows:result.rows});}));
app.post('/api/import/commit',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader']);if(req.body.confirm!==true)throw fail('Cần xác nhận nhập dữ liệu');if(!['skip','update','new'].includes(req.body.mode))throw fail('Chọn cách xử lý dữ liệu trùng');const {draft,rows}=await importRows(req);if(rows.some(r=>r.errors.length))throw fail('Hãy sửa tất cả dòng lỗi trước khi nhập');let added=0,updated=0,skipped=0;for(const row of rows){const products=await db.all('products'),dup=duplicate(row.p,products);if(dup&&req.body.mode==='skip'){skipped++;continue;}if(dup&&req.body.mode==='update'){await saveProduct(req,{...dup,...row.p},dup.id,true,true);updated++;}else{const p={...row.p};if(dup){p.code=p.code+'-'+crypto.randomBytes(3).toString('hex').toUpperCase();}await saveProduct(req,p,null,true,true);added++;}}const imported=await db.all('products');for(const rival of imported.filter(p=>!D.own(p)))await refreshMatches(rival,imported);const record={id:crypto.randomUUID(),file:draft.file,at:now(),by:req.user.name,added,updated,skipped,mode:req.body.mode,raw:draft.rows,mapping:req.body.mapping};await db.put('imports',record);await db.remove('importDrafts',draft.id);res.json({added,updated,skipped});})));
app.post('/api/enrich-specs',asyncRoute(async(req,res)=>{permit(req,['admin','leader','sales']);res.json(enrichProductSpecs(req.body));}));
app.post('/api/enrich-all',asyncRoute(async(req,res)=>db.transaction(async()=>{permit(req,['admin','leader']);const products=await db.all('products');let updated=0;for(const p of products){const enriched=enrichProductSpecs(p);await db.put('products',enriched);updated++;}const all=await db.all('products');for(const rival of all.filter(p=>!D.own(p)))await refreshMatches(rival,all);await audit(req.user,'Làm giàu thông số tự động',`${updated} sản phẩm`);res.json({success:true,count:updated});})));
app.get('/api/report.xlsx',asyncRoute(async(req,res)=>{const p=await db.all('products'),weights=await settings(),ids=String(req.query.ids||'').split(',').filter(Boolean);const selected=p.filter(q=>(!ids.length||ids.includes(q.id))&&(!req.query.category||q.category===req.query.category));const visible=D.fields.filter(f=>D.canFinance(req.user.role)||!D.privateKeys.includes(f.key));const wb=XLSX.utils.book_new();const rows=selected.map(q=>{const out=Object.fromEntries(visible.map(f=>[f.label,q[f.key]??'']));const s=D.competition(q,p,weights);out['Điểm cạnh tranh']=s.score??'Chưa đủ dữ liệu';out['Độ đầy đủ (%)']=s.confidence;out['Thiếu đánh giá']=s.missing.map(k=>D.scoreLabels[k]).join(', ');out['Ngày cập nhật']=q.updatedAt;out['Nguồn dữ liệu']=q.source||'Chưa có';if(D.canFinance(req.user.role)){const f=D.finance(q);out['Lợi nhuận ròng / sp']=f.net??'Chưa đủ dữ liệu';out['Giá hòa vốn']=f.breakEven??'';out['Doanh thu dự kiến']=f.revenue??'';out['Đề xuất']=D.recommendation(q,p,weights).label;}return out;});XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Sản phẩm');const meta=[['VŨ GIA — BÁO CÁO SẢN PHẨM'],['Ngày lập',now()],['Người lập',req.user.name],['Số sản phẩm',selected.length],['Kết luận',String(req.query.conclusion||'Đánh giá theo dữ liệu và trọng số tại thời điểm xuất.')],['Đề xuất hành động',String(req.query.suggestion||'Bổ sung dữ liệu còn thiếu; kiểm chứng nguồn trước khi phê duyệt.')],['Phê duyệt Ban lãnh đạo','................................']];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(meta),'Thông tin báo cáo');const ms=await db.all('matches');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(ms.filter(m=>selected.some(p=>p.id===m.id)).flatMap(m=>m.ids.map(id=>{const a=p.find(p=>p.id===m.id),b=p.find(p=>p.id===id);return {'Đối thủ':a?.code,'Lock&King':b?.code,'Điểm':a&&b?D.similarity(a,b).score:'','Lý do':a&&b?D.similarity(a,b).reason:'','Trạng thái':m.status};}))), 'Ghép cặp');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(selected.filter(q=>!D.own(q)&&D.gap(q,p)).map(q=>({'Sản phẩm':q.name,'Phân loại':D.gap(q,p)==='confirmed'?'Chưa có tương đương':'Chưa đủ dữ liệu','Giá online':q.online??''}))), 'Cơ hội');const history=selected.flatMap(q=>(q.priceHistory||[]).flatMap(h=>h.changes.filter(c=>D.canFinance(req.user.role)||!D.privateKeys.includes(c.field)).map(c=>({'Mã':q.code,'Thời gian':h.at,'Người sửa':h.by,'Trường':D.labels[c.field],'Trước':c.before,'Sau':c.after}))));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(history),'Lịch sử giá');for(const name of wb.SheetNames)wb.Sheets[name]['!cols']=Array.from({length:110},()=>({wch:24}));sendWorkbook(res,wb,'Bao-cao-Vu-Gia.xlsx');}));
app.use('/api',(req,res)=>res.status(404).json({error:'Không tìm thấy chức năng'}));
if(fs.existsSync('dist/index.html')){app.use(express.static('dist'));app.get('*',(req,res)=>res.sendFile(path.resolve('dist/index.html')));}else{const {createServer}=await import('vite');const vite=await createServer({server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);}
app.use((err,req,res,next)=>{console.error(err.message);res.status(err.status||400).json({error:err.message||'Không thể xử lý yêu cầu'});});
app.listen(port,process.env.HOST||'127.0.0.1',()=>console.log(`Vũ Gia V2: http://localhost:${port} · ${db.dbMode}`));

