import React,{useState,useMemo} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import * as D from '../shared/domain.js';
import {brandKey,listBrands,sheetName,initialBrands} from '../shared/brands.js';
import {comparisonPriceGroups,comparisonPrices} from '../shared/price-comparison.js';
import './style.css';

const initial=window.VUGIA_SEED||{products:[],brands:initialBrands.map(name=>({name})),images:{}};
const clone=v=>JSON.parse(JSON.stringify(v));
const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
const money=v=>D.has(v)?Number(v).toLocaleString('vi-VN')+' ₫':'—';
const readFile=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Không đọc được tệp'));r.readAsDataURL(f);});
function saveFile(data,name,type){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
let database;
async function storage(){return database||(database=await new Promise((resolve,reject)=>{const r=indexedDB.open('vugia-offline-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Đóng tab Vũ Gia khác rồi mở lại'));}));}
async function read(){const db=await storage();return new Promise((resolve,reject)=>{const r=db.transaction('data').objectStore('data').get('state');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function write(state){const db=await storage();return new Promise((resolve,reject)=>{const t=db.transaction('data','readwrite');t.objectStore('data').put(state,'state');t.oncomplete=resolve;t.onabort=t.onerror=()=>reject(t.error||Error('Không lưu được dữ liệu'));});}
const imageURL=(src,images)=>images[src]||(/^(https?:|data:image\/(png|jpeg|webp|gif);base64,)/i.test(src||'')?src:'');
function Picture({p,images}){const src=imageURL(p.image,images);return src?<img src={src} loading="lazy" alt={p.name}/>:<div className="no-image">Chưa có ảnh</div>;}
const valid=p=>D.validate({...p,image:'',images:'',packaging:''});
function PriceSummary({selected}){return <>{comparisonPriceGroups.filter(g=>selected.some(p=>comparisonPrices(p,g).length)).map(g=><tr key={g.key}><th>{g.label}</th>{selected.map(p=><td key={p.id}>{comparisonPrices(p,g).length?comparisonPrices(p,g).map(v=><div key={v.key}><strong>{money(v.value)}</strong><br/><small>{v.label}</small></div>):'Chưa có giá loại này'}</td>)}</tr>)}</>;}
function App({loaded,storageError}){
 const [state,setState]=useState(loaded),[tab,setTab]=useState('catalog'),[brand,setBrand]=useState('all'),[query,setQuery]=useState(''),[missing,setMissing]=useState(false),[edit,setEdit]=useState(null),[detail,setDetail]=useState(null),[chosen,setChosen]=useState([]),[notice,setNotice]=useState(storageError||''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(null),[mode,setMode]=useState('update');
 const brands=useMemo(()=>listBrands(state.brands,state.products),[state]);
 const products=useMemo(()=>state.products.filter(p=>(brand==='all'||brandKey(p.brand)===brand)&&(!missing||!p.image)&&D.norm([p.code,p.model,p.name,p.category,p.brand].join(' ')).includes(D.norm(query))),[state,brand,query,missing]);
 const selected=state.products.filter(p=>chosen.includes(p.id));
 const prices=D.catalogPriceKeys.filter(k=>state.products.some(p=>D.has(p[k])));
 async function commit(next){setBusy(true);try{await write(next);setState(next);setNotice('Đã lưu trên trình duyệt này.');return true;}catch(e){setNotice('Chưa lưu được: '+e.message+'. Hãy tải bản sao lưu trước khi đóng trang.');return false;}finally{setBusy(false);}}
 function backup(){saveFile(JSON.stringify({format:'vugia-offline',version:1,at:new Date().toISOString(),...state}),'Vu-Gia-sao-luu-'+new Date().toISOString().slice(0,10)+'.json','application/json');setNotice('Đã tạo tệp sao lưu gồm sản phẩm, giá và ảnh.');}
 async function restore(file){if(!file)return;try{const b=JSON.parse(await file.text());if(b.format!=='vugia-offline'||b.version!==1||!Array.isArray(b.products)||!Array.isArray(b.brands)||!b.images||typeof b.images!=='object')throw Error('Tệp sao lưu không đúng định dạng');if(b.products.some(p=>!p.id||!p.code||!p.name||!p.brand)||new Set(b.products.map(p=>p.id)).size!==b.products.length)throw Error('Danh mục sao lưu không hợp lệ');if(!confirm('Thay dữ liệu hiện tại bằng '+b.products.length+' sản phẩm trong bản sao lưu?'))return;if(await commit({products:b.products,brands:b.brands,images:b.images})){setChosen([]);setBrand('all');}}catch(e){setNotice(e.message);}}
 async function saveProduct(e){e.preventDefault();const errors=valid(edit);if(errors.length){setNotice(errors.map(e=>D.labels[e.field]+': '+e.message).join('; '));return;}if(state.products.some(p=>p.id!==edit.id&&brandKey(p.brand)===brandKey(edit.brand)&&D.norm(p.code)===D.norm(edit.code))){setNotice('Mã này đã tồn tại trong hãng.');return;}const old=state.products.find(p=>p.id===edit.id),p={...edit,id:edit.id||uid(),updatedAt:new Date().toISOString()};const changes=D.fields.filter(f=>f.type==='money'&&old?.[f.key]!==p[f.key]).map(f=>({field:f.key,before:old?.[f.key]??null,after:p[f.key]??null}));p.priceHistory=[...(old?.priceHistory||[]),...(changes.length?[{at:p.updatedAt,by:'Bản HTML',changes}]:[])];if(await commit({...state,products:old?state.products.map(x=>x.id===p.id?p:x):[...state.products,p]}))setEdit(null);}
 async function addBrands(){const names=prompt('Nhập tên các hãng, ngăn cách bằng dấu phẩy hoặc xuống dòng:');if(!names)return;const list=names.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);if(list.some(n=>n.length>120)||list.length>1000){setNotice('Tối đa 1.000 hãng, mỗi tên tối đa 120 ký tự.');return;}const keys=new Set(brands.map(b=>b.key));await commit({...state,brands:[...state.brands,...list.filter(n=>{const k=brandKey(n);if(keys.has(k))return false;keys.add(k);return true;}).map(name=>({name}))]});}
 function exportExcel(all){const wb=XLSX.utils.book_new(),used=new Set();for(const b of brands.filter(b=>all||brand==='all'||b.key===brand)){const rows=(all?state.products:products).filter(p=>brandKey(p.brand)===b.key);const sh=XLSX.utils.aoa_to_sheet([D.fields.map(f=>f.label),...rows.map(p=>D.fields.map(f=>String(p[f.key]??'').startsWith('data:image/')?'Ảnh lưu trong bản sao lưu JSON':p[f.key]??''))]);sh['!cols']=D.fields.map(f=>({wch:f.key==='name'?45:22}));XLSX.utils.book_append_sheet(wb,sh,sheetName(b.name,used));}if(!wb.SheetNames.length)XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([D.fields.map(f=>f.label)]),'Sản phẩm');saveFile(XLSX.write(wb,{type:'array',bookType:'xlsx'}),'Vu-Gia-Moi-Hang-Mot-Sheet.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
 function template(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([D.fields.map(f=>f.label)]),'Sản phẩm');saveFile(XLSX.write(wb,{type:'array',bookType:'xlsx'}),'Mau-nhap-Vu-Gia.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
 async function importExcel(file){if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:true});const rows=[];for(const name of wb.SheetNames){const sh=wb.Sheets[name],matrix=XLSX.utils.sheet_to_json(sh,{header:1,defval:''});if(!matrix.length)continue;const mapping=matrix[0].map(h=>D.fields.find(f=>D.norm(f.label)===D.norm(h)||D.norm(f.key)===D.norm(h))?.key);if(!['code','name','brand','category'].every(k=>mapping.includes(k)))continue;if(new Set(mapping.filter(Boolean)).size!==mapping.filter(Boolean).length)throw Error('Cột trùng trong sheet '+name);if(Object.values(sh).some(v=>v?.f))throw Error('Hãy chuyển công thức thành giá trị trước khi nhập: '+name);for(let i=1;i<matrix.length;i++){if(!matrix[i].some(D.has))continue;const p={};mapping.forEach((key,j)=>{if(key){let v=matrix[i][j]??'';if(D.numeric.includes(key)&&D.has(v)){let s=String(v).replace(/\s|₫|đ|VND/gi,'');if(/^\d{1,3}([.,]\d{3})+$/.test(s))s=s.replace(/[.,]/g,'');else s=s.replace(',','.');v=Number(s);}p[key]=v;}});rows.push({p,where:name+' · dòng '+(i+1),errors:valid(p)});}}if(!rows.length)throw Error('Không tìm thấy sheet có đủ cột Mã sản phẩm, Tên sản phẩm, Thương hiệu, Nhóm ngành hàng.');if(rows.length>5000)throw Error('Tối đa 5.000 sản phẩm mỗi lần.');setPreview(rows);}catch(e){setNotice(e.message);}}
 async function acceptImport(){const ps=clone(state.products);for(const {p} of preview){const at=ps.findIndex(x=>brandKey(x.brand)===brandKey(p.brand)&&D.norm(x.code)===D.norm(p.code));if(at>=0){if(mode==='update'){const incoming={...p};if(String(incoming.image).startsWith('Ảnh lưu'))delete incoming.image;ps[at]={...ps[at],...incoming,updatedAt:new Date().toISOString()};}}else ps.push({...p,id:uid()});}if(await commit({...state,products:ps}))setPreview(null);}
 return <><header><div><strong>VŨ GIA</strong><span>So sánh sản phẩm · Bản HTML</span></div><nav><button onClick={()=>setTab('catalog')} className={tab==='catalog'?'active':''}>Danh mục hãng</button><button onClick={()=>setTab('compare')} className={tab==='compare'?'active':''}>So sánh ({chosen.length})</button><button onClick={()=>setTab('backup')}>Sao lưu & nhập dữ liệu</button></nav></header>
 <div className="local-note">Chạy trực tiếp trên máy · Dữ liệu lưu trong trình duyệt · Không cần đăng nhập <button onClick={backup}>Tải bản sao lưu</button></div>
 {notice&&<div role="status" className="notice">{notice}<button onClick={()=>setNotice('')}>Đóng</button></div>}
 <main><div className="heading"><div><h1>{tab==='catalog'?'Danh mục sản phẩm':tab==='compare'?'So sánh sản phẩm':'Sao lưu & nhập dữ liệu'}</h1><p>{state.products.length} sản phẩm · {brands.length} hãng · {state.products.filter(p=>!p.image).length} sản phẩm chưa có ảnh</p></div><button className="primary" onClick={()=>setEdit({brand:brands.find(b=>b.key===brand)?.name||'',category:''})}>+ Thêm sản phẩm</button></div>
 {tab==='catalog'&&<div className="layout"><aside><button className={brand==='all'?'active':''} onClick={()=>setBrand('all')}>Tất cả hãng <b>{state.products.length}</b></button>{brands.map(b=><button key={b.key} className={brand===b.key?'active':''} onClick={()=>setBrand(b.key)}>{b.name}<b>{b.count}</b></button>)}<button onClick={addBrands}>+ Thêm danh sách hãng</button></aside><section><div className="toolbar"><input aria-label="Tìm sản phẩm" placeholder="Tìm tên, mã, hãng…" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={missing} onChange={e=>setMissing(e.target.checked)}/> Thiếu ảnh</label><button onClick={()=>exportExcel(false)}>Xuất Excel</button></div><p>{products.length} sản phẩm</p><div className="cards">{products.map(p=><article key={p.id}><button className="picture" onClick={()=>setDetail(p)}><Picture p={p} images={state.images}/></button><div className="card-body"><small>{p.brand} · {p.code}</small><h3><button onClick={()=>setDetail(p)}>{p.name}</button></h3><dl>{prices.filter(k=>D.has(p[k])).map(k=><div key={k}><dt>{D.labels[k]}</dt><dd>{money(p[k])}</dd></div>)}</dl><footer><label><input type="checkbox" checked={chosen.includes(p.id)} onChange={()=>setChosen(chosen.includes(p.id)?chosen.filter(id=>id!==p.id):chosen.length<5?[...chosen,p.id]:(setNotice('Chọn tối đa 5 sản phẩm để so sánh.'),chosen))}/> So sánh</label><button onClick={()=>setEdit(clone(p))}>Sửa</button></footer></div></article>)}</div>{!products.length&&<div className="empty">Chưa có sản phẩm phù hợp. Bạn có thể thêm sản phẩm hoặc nhập Excel.</div>}</section></div>}
 {tab==='compare'&&(selected.length?<><div className="toolbar"><button onClick={()=>window.print()}>In / lưu PDF</button><button onClick={()=>setChosen([])}>Bỏ chọn tất cả</button></div><div className="table-wrap"><table><thead><tr><th>Tiêu chí</th>{selected.map(p=><th key={p.id}><Picture p={p} images={state.images}/><p>{p.name}</p><small>{p.brand} · {p.code}</small></th>)}</tr></thead><tbody><PriceSummary selected={selected}/>{D.fields.filter(f=>f.group!=='media'&&selected.some(p=>D.has(p[f.key]))).map(f=><tr key={f.key}><th>{f.label}</th>{selected.map(p=><td key={p.id}>{f.type==='money'?money(p[f.key]):String(p[f.key]??'—')}</td>)}</tr>)}<tr><th>Lợi nhuận ròng / sản phẩm</th>{selected.map(p=><td key={p.id}>{money(D.finance(p).net)}</td>)}</tr></tbody></table></div><p>Lợi nhuận chỉ hiển thị khi có đủ dữ liệu tính toán.</p></>:<div className="empty">Chọn từ 2 đến 5 sản phẩm trong danh mục để xem bảng so sánh.</div>)}
 {tab==='backup'&&<div className="panels"><section><h2>Sao lưu dữ liệu và ảnh</h2><p>Dữ liệu chỉ lưu trên trình duyệt và máy này. Hãy tải bản sao lưu trước khi đổi máy, đổi trình duyệt hoặc xóa dữ liệu duyệt web.</p><button className="primary" onClick={backup}>Tải bản sao lưu JSON</button><label className="file">Khôi phục bản sao lưu<input type="file" accept=".json" onChange={e=>{restore(e.target.files[0]);e.target.value='';}}/></label></section><section><h2>Bảng giá Excel</h2><p>Mỗi hãng có một sheet riêng. Có thể nhập nhiều sheet có cùng bộ cột trong một lần.</p><button onClick={()=>exportExcel(true)}>Xuất tất cả hãng</button><button onClick={template}>Tải Excel mẫu</button><label className="file">Nhập file Excel<input type="file" accept=".xlsx,.xls,.csv" onChange={e=>{importExcel(e.target.files[0]);e.target.value='';}}/></label><p>Excel chứa thông tin và đường dẫn ảnh. Dùng bản sao lưu JSON để chuyển cả ảnh sang máy khác.</p></section></div>}
 </main>
 {detail&&<div className="overlay"><section className="modal"><button className="close" onClick={()=>setDetail(null)}>Đóng</button><h2>{detail.name}</h2><div className="detail-picture"><Picture p={detail} images={state.images}/></div><dl>{D.fields.filter(f=>D.has(detail[f.key])&&!['image','images','packaging'].includes(f.key)).map(f=><div key={f.key}><dt>{f.label}</dt><dd>{f.type==='money'?money(detail[f.key]):String(detail[f.key])}</dd></div>)}</dl>{detail.imageSource?.page&&<p>Nguồn ảnh: <a href={/^https?:/.test(detail.imageSource.page)?detail.imageSource.page:undefined} target="_blank" rel="noreferrer">Website hãng</a></p>}<button onClick={()=>{setEdit(clone(detail));setDetail(null);}}>Chỉnh sửa</button></section></div>}
 {edit&&<div className="overlay"><form className="modal" onSubmit={saveProduct}><div className="modal-head"><h2>{edit.id?'Sửa sản phẩm':'Thêm sản phẩm'}</h2><button type="button" onClick={()=>setEdit(null)}>Đóng</button></div><label className="file">Chọn ảnh từ máy<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={async e=>{const f=e.target.files[0];if(f){if(f.size>10*1024*1024){setNotice('Ảnh tối đa 10 MB.');return;}setEdit({...edit,image:await readFile(f)});}}}/></label>{edit.image&&<div className="detail-picture"><Picture p={edit} images={state.images}/></div>}{Object.entries(D.groups).map(([g,label])=><details key={g} open={g==='basic'||g==='prices'}><summary>{label}</summary><div className="form-grid">{D.fields.filter(f=>f.group===g).map(f=><label key={f.key}>{f.label}<input required={['code','name','brand','category'].includes(f.key)} type={D.numeric.includes(f.key)?'number':f.type==='date'?'date':'text'} step="any" min={D.numeric.includes(f.key)?0:undefined} value={edit[f.key]??''} onChange={e=>setEdit({...edit,[f.key]:D.numeric.includes(f.key)&&e.target.value!==''?Number(e.target.value):e.target.value})}/></label>)}</div></details>)}<div className="modal-foot"><button type="submit" className="primary" disabled={busy}>Lưu sản phẩm</button>{edit.id&&<button type="button" onClick={async()=>{if(confirm('Xóa sản phẩm '+edit.code+'?')&&await commit({...state,products:state.products.filter(p=>p.id!==edit.id)})){setChosen(chosen.filter(id=>id!==edit.id));setEdit(null);}}}>Xóa sản phẩm</button>}</div></form></div>}
 {preview&&<div className="overlay"><section className="modal"><h2>Xem trước nhập Excel</h2><p>{preview.length} dòng · {preview.filter(r=>r.errors.length).length} dòng lỗi</p><label>Nếu trùng mã trong cùng hãng: <select value={mode} onChange={e=>setMode(e.target.value)}><option value="update">Cập nhật (ô trống cũng ghi đè)</option><option value="skip">Bỏ qua sản phẩm đã có</option></select></label><div className="table-wrap"><table><tbody>{preview.slice(0,100).map((r,i)=><tr key={i}><td>{r.where}</td><td>{r.p.code}</td><td>{r.p.name}</td><td>{r.errors.map(e=>D.labels[e.field]+': '+e.message).join('; ')||'Hợp lệ'}</td></tr>)}</tbody></table></div><button className="primary" disabled={busy||preview.some(r=>r.errors.length)} onClick={acceptImport}>Xác nhận nhập</button><button onClick={()=>setPreview(null)}>Hủy</button></section></div>}
 </>;
}
async function boot(){let state,storageError;try{state=await read();if(!state){state=clone(initial);await write(state);}}catch(e){state=clone(initial);storageError='Trình duyệt không cho lưu dữ liệu: '+e.message+'. Hãy dùng Chrome/Edge và cho phép lưu dữ liệu.';}createRoot(document.getElementById('root')).render(<App loaded={state} storageError={storageError}/>);}
boot().catch(e=>{document.getElementById('root').textContent='Không mở được phần mềm: '+e.message;});
