// @ts-nocheck
import React,{useEffect,useMemo,useState} from 'react';
import {Search,Plus,Download,Building2,ChevronRight,X} from 'lucide-react';
import {brandKey} from '../shared/brands.js';
import './brands.css';
export default function BrandSheets({products,user,notify,setEditing,renderCatalog}){
 const[brands,setBrands]=useState([]),[active,setActive]=useState('lockking'),[search,setSearch]=useState(''),[adding,setAdding]=useState(false),[names,setNames]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){try{const r=await fetch('/api/brands');const data=await r.json();if(!r.ok)throw Error(data.error);setBrands(data);setError('');}catch(e){setError(e.message);}}
 useEffect(()=>{refresh()},[products]);
 const current=brands.find(b=>b.key===active)||brands[0];
 const matching=useMemo(()=>products.filter(p=>brandKey(p.brand)===current?.key),[products,current?.key]);
 const filtered=brands.filter(b=>brandKey(b.name).includes(brandKey(search)));
 async function save(e){e.preventDefault();setBusy(true);try{const res=await fetch('/api/brands',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({names})});const result=await res.json();if(!res.ok)throw Error(result.error);await refresh();setAdding(false);setNames('');notify('Đã thêm '+result.added+' hãng; bỏ qua '+result.skipped+' hãng đã tồn tại.');}catch(e){notify(e.message);}finally{setBusy(false)}}
 return <><div className="brand-workspace-actions"><span><strong>{brands.length}</strong> hãng · <strong>{products.length}</strong> sản phẩm</span><div className="inline-actions"><a className="button" href="/api/brands.xlsx"><Download size={16}/>Xuất mỗi hãng 1 sheet</a>{['admin','leader'].includes(user.role)&&<button className="primary" onClick={()=>setAdding(true)}><Plus size={16}/>Thêm danh sách hãng</button>}</div></div>{error&&<div className="notice error">{error}<button onClick={refresh}>Thử lại</button></div>}<div className="brand-workspace"><aside className="brand-index panel"><div className="brand-search"><Search size={17}/><input aria-label="Tìm tên hãng" placeholder="Tìm trong danh sách hãng…" value={search} onChange={e=>setSearch(e.target.value)}/></div><div role="tablist" aria-label="Danh sách hãng" aria-orientation="vertical" className="brand-tabs">{filtered.map(b=><button key={b.key} id={'brand-tab-'+encodeURIComponent(b.key)} role="tab" aria-selected={current?.key===b.key} aria-controls="brand-products-panel" onClick={()=>setActive(b.key)}><Building2 size={16}/><span>{b.name}</span><b>{b.count}</b><ChevronRight size={14}/></button>)}</div>{!filtered.length&&<p className="muted padded">Không tìm thấy hãng.</p>}</aside><section role="tabpanel" id="brand-products-panel" aria-labelledby={current?'brand-tab-'+encodeURIComponent(current.key):undefined} className="brand-products"><div className="brand-current"><div><h2>{current?.name||'Danh mục hãng'}</h2><p>{matching.length} sản phẩm thuộc hãng này</p></div><div className="inline-actions">{current&&<a className="button" href={'/api/brands.xlsx?brand='+encodeURIComponent(current.name)}><Download size={16}/>Xuất hãng này</a>}{current&&['admin','leader'].includes(user.role)&&<button onClick={()=>setEditing({brand:current.name})}><Plus size={16}/>Thêm sản phẩm</button>}</div></div>{current&&renderCatalog(matching,current.name)}</section></div>{adding&&<div className="modal-backdrop"><form className="modal compact" onSubmit={save}><div className="modal-head"><h2>Thêm danh sách hãng</h2><button type="button" className="icon-button" aria-label="Đóng" onClick={()=>setAdding(false)}><X size={18}/></button></div><div className="padded"><label>Mỗi dòng một hãng, hoặc ngăn cách bằng dấu phẩy<textarea rows={12} autoFocus value={names} onChange={e=>setNames(e.target.value)} placeholder={'Jiwon\nMorico\nHare\nHatzz'}/></label><p className="small muted">Có thể dán khoảng 100 hãng cùng lúc. Tên trùng được bỏ qua; hãng mới có sheet trống để bạn nhập sản phẩm.</p></div><div className="modal-foot"><button type="button" onClick={()=>setAdding(false)}>Hủy</button><button disabled={busy||!names.trim()} className="primary">{busy?'Đang lưu…':'Tạo các sheet hãng'}</button></div></form></div>}</>;
}
